name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false

    - name: Build
      run: go build -v ./...
      working-directory: ./url-shortener

    - name: Vet
      run: go vet ./...
      working-directory: ./url-shortener

    - name: Build Docker image
      run: docker build -t url-shortener:latest .
      working-directory: ./url-shortener