name: CI Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v5
      with:
        go-version: '1.23'
        cache: false
    - run: go build -v ./...
      working-directory: ./url-shortener
    - run: go vet ./...
      working-directory: ./url-shortener
    - run: docker build -t url-shortener:latest .
      working-directory: ./url-shortener
